dashboard:
  image: cjackson/iso-deck-tracker
  ports:
   - "80:3000"
  links:
   - mongo-dev:mongo-dev
  environment:
   - MONGO_URL=mongodb://isodecktracker2_mongo-dev_1/iso-deck-tracker
   - ROOT_URL=http://54.85.165.254
   - DELAY=30
   - PORT=3000
mongo-dev:
  image: tozd/meteor-mongodb
  ports:
   - "27017:27017"